Update references from HPCng to Apptainer
apptainer/apptainer-admindocs pull request #17
Opened 2022-02-16 22:58 UTC by pedroalvesbatista

Signed-off-by: Pedro Alves Batista <pedro.pesquisapb@gmail.com>

Replaces any reference of HPCng to Apptainer.

* Fixes:
#7

2022-02-16 23:20 UTC, DrDaveD requested changes
Let's use `{orgrepo}` instead of `apptainer/apptainer` like we did with the userdocs.

2022-02-18 19:39 UTC, DrDaveD requested changes
A conflict needs to be resolved

2022-02-18 19:39 UTC, DrDaveD commented on conf.py
>      'github_repo': 'singularity-admindocs',
Change this to apptainer-admindocs

2022-02-18 19:42 UTC, pedroalvesbatista commented on conf.py
>      'github_repo': 'singularity-admindocs',
Any other Singularity references will do in another PR, as there are some of them remaining.

2022-02-18 19:44 UTC, pedroalvesbatista commented on conf.py
>      'github_repo': 'singularity-admindocs',
In #21 more specifically, as there are more references out there.

2022-02-18 21:27 UTC, DrDaveD approved these changes

2022-02-18 21:27 UTC, merged