Replaces singularity in CLI examples
apptainer/apptainer-admindocs pull request #19
Opened 2022-02-16 23:39 UTC by pedroalvesbatista

Signed-off-by: Pedro Alves Batista <pedro.pesquisapb@gmail.com>

Replaces `singularity` to `{command}` in CLI examples.

* Fixes:
#13

2022-02-17 20:15 UTC, DrDaveD commented on admin_quickstart.rst
> +        wget https://github.com/hpcng/{command}/releases/download/v${VERSION}/{command}-${VERSION}.tar.gz && \
This github URL should use `{orgrepo}` instead (in another PR)

2022-02-17 20:15 UTC, DrDaveD commented on appendix.rst
> +   bin/run-{command} root:root 755 (-rwxr-xr-x)
This one has to stay as `run-singularity`

2022-02-17 20:16 UTC, DrDaveD commented on conf.py
> +    'github_repo': '{command}-admindocs',
Make this apptainer, I found that conf.py does not support replacements.

2022-02-17 20:17 UTC, DrDaveD commented on conf.py
> +    'github_repo': '{command}-admindocs',
Likewise several other cases in this file below.

2022-02-17 20:18 UTC, DrDaveD commented on conf.py
> +epub_identifier = 'https://github.com/hpcng/{command}-admindocs'
Leave this for the PR on github URL

2022-02-17 20:27 UTC, DrDaveD commented on conf.py
> +lexers['{command}'] = SingularityLexer(startinline=True)
In order to convert the lexer a lot more has to be done as in the second commit of apptainer/apptainer-userdocs#54.  However, I do not see anything of the form
```
.. code:: {command}
```
so I think the lexer isn't actually used and can be deleted.

2022-02-17 20:27 UTC, DrDaveD commented on installation.rst
> +<https://github.com/hpcng/{command}/releases>`_. After deciding on a
Don't change github URL in this PR

2022-02-17 20:28 UTC, DrDaveD commented on installation.rst
> +       /usr/local/bin/run-{command} \
this stays at run-singularity

2022-02-17 20:29 UTC, DrDaveD commented on installation.rst
> +   $ export VM=sylabs/{command}-3.8-ubuntu-bionic64 && \
There was no apptainer-3.8 so this might as well stay at sylabs/singularity for now.

2022-02-17 20:32 UTC, DrDaveD commented on installation.rst
>         wget https://github.com/hpcng/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
This one should have `{command}` as part of the file name at the end instead of singularity

2022-02-18 20:20 UTC, pedroalvesbatista commented on conf.py
> +lexers['{command}'] = SingularityLexer(startinline=True)
Delete this whole part regarding lexer and wipe out any reference to it (like this `.. code::` sections) ?

2022-02-18 21:36 UTC, DrDaveD commented on conf.py
> +lexers['{command}'] = SingularityLexer(startinline=True)
Delete references to the lexer and pygments here in conf.py and remove pygments_singularity.py.  The `.. code::` sections that are there stay the same; the point is that none of them refer to a lexer called `{command}` like many of the code sections did in userdocs.

2022-02-18 21:42 UTC, DrDaveD requested changes
There are conflicts to resolve too

2022-02-18 21:42 UTC, DrDaveD commented on conf.py
> +epub_identifier = 'https://github.com/hpcng/apptainer-admindocs'
There is no such thing as hpcng/apptainer.  Anyway this will be done in a different PR.

2022-02-18 21:42 UTC, DrDaveD commented on configfiles.rst
> +>>>>>>> Replaces singularity to {command} in CLI examples #13
Fix unresolved merge.

2022-02-21 01:00 UTC, ikaneshiro commented on admin_quickstart.rst
> +>>>>>>> 162907d... Replaces singularity to {command} in CLI examples #13
This merge conflict needs to be resolved

2022-02-21 19:50 UTC, ikaneshiro approved these changes

2022-02-21 19:59 UTC, pedroalvesbatista commented on conf.py
> +lexers['{command}'] = SingularityLexer(startinline=True)
Then the `.. code::` sections can be backed to `apptainer` instead of `{command}` ?

2022-02-21 21:04 UTC, DrDaveD approved these changes

2022-02-21 21:05 UTC, DrDaveD commented on conf.py
> +lexers['{command}'] = SingularityLexer(startinline=True)
The point is that there aren't any in admindocs like there were in userdocs.

2022-02-21 21:06 UTC, merged