Separating installation procedures for Debian and Ubuntu
apptainer/apptainer-admindocs pull request #96
Opened 2023-01-25 02:20 UTC by panda1100

Signed-off-by: Yoshiaki Senda yoshiaki@live.it

2023-01-25 02:36 UTC, DrDaveD requested changes
The new Debian install instructions look OK, but while you're at it fix up the Ubuntu instructions for starting from a minimal image.

2023-01-25 02:36 UTC, DrDaveD commented on installation.rst
>  .. code::
I tried the Ubuntu instructions in a fresh ubuntu:22.04 docker container and got the following:
```
# add-apt-repository -y ppa:apptainer/ppa
bash: add-apt-repository: command not found
```
I think the Ubuntu instructions need some more for bootstrapping on a fresh install.

2023-01-25 03:48 UTC, panda1100 commented on installation.rst
>  .. code::
Yes, That is true for container. Desktop/Sever version of Ubuntu has `add-apt-repository` command out of the box. 
I updated my PR.

2023-01-25 03:58 UTC, panda1100 commented
Sorry, I squashed commits and signed-off, Could you please help me to re-run DCO check?

2023-01-25 15:59 UTC, DrDaveD requested changes
I believe the problem with the DCO test is the format of the Sign-off.  It expects the email address to be surrounded by brackets `<>`.

I generally think it is a good idea to squash commits and force-push as you did, that's good.  If you don't do it I usually do a squash & merge.

2023-01-25 15:59 UTC, DrDaveD commented on installation.rst
> +First, on Ubuntu based container install `software-properties-common` package to obtain `add-apt-repository` command. On Ubuntu Desktop/Sever derived systems skip this step.
Typo "Sever" -> "Server".  Also change "container" to "containers".

2023-01-25 15:59 UTC, DrDaveD commented on installation.rst
> +    $ apt update
This needs a sudo.  Also, some of the instructions on this page say "apt update" and some say "apt-get update".  Please choose one and make them consistent.

2023-01-26 00:17 UTC, panda1100 commented on installation.rst
> +First, on Ubuntu based container install `software-properties-common` package to obtain `add-apt-repository` command. On Ubuntu Desktop/Sever derived systems skip this step.
Thank you!

2023-01-26 00:19 UTC, panda1100 commented on installation.rst
> +    $ apt update
I added `sudo` and made those consistent.

2023-01-26 17:44 UTC, DrDaveD approved these changes

2023-01-26 17:44 UTC, merged

2023-01-26 17:45 UTC, DrDaveD commented
Great, now please submit the prior PR and this one to the 1.1 branch too.

2023-01-26 23:09 UTC, panda1100 commented
Will do! Thank you